dev: Provide better feedback when importing users
Write better messaging around what the REDCap API returns when you
import a user, and specify which project tokens fail to import users in
the "add user to all projects" script.

diff --git a/dev/add-user-to-all-projects b/dev/add-user-to-all-projects
--- a/dev/add-user-to-all-projects
+++ b/dev/add-user-to-all-projects
@@ -17,40 +17,45 @@ set -euo pipefail
 
 
 for token in \
-    "$REDCAP_API_TOKEN_SFS_KIOSK" \
-    "$REDCAP_API_TOKEN_SFS_SHELTERS" \
-    "$REDCAP_API_TOKEN_SFS_SWAB_N_SEND" \
-    "$REDCAP_API_TOKEN_SFS_SHELTERS" \
-    "$REDCAP_API_TOKEN_SWAB_N_SEND_HEALTHCARE_WORKER" \
-    "$REDCAP_API_TOKEN_SFS_ASYMPTOMATIC" \
-    "$REDCAP_API_TOKEN_SFS_SWAB_N_SEND_HOME_FLU" \
-    "$REDCAP_API_TOKEN_SWAB_N_SEND_ASYMPTOMATIC" \
-    "$REDCAP_API_TOKEN_SCAN_EN" \
-    "$REDCAP_API_TOKEN_SCAN_VI" \
-    "$REDCAP_API_TOKEN_SCAN_ZH_HANS" \
-    "$REDCAP_API_TOKEN_SCAN_ES" \
-    "$REDCAP_API_TOKEN_SCAN_ZH_HANT" \
-    "$REDCAP_API_TOKEN_SCAN_RU" \
-    "$REDCAP_API_TOKEN_SCAN_SO" \
-    "$REDCAP_API_TOKEN_SCAN_KO" \
-    "$REDCAP_API_TOKEN_SCAN_AM" \
-    "$REDCAP_API_TOKEN_SCAN_TI" \
-    "$REDCAP_API_TOKEN_SCAN_TL" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_EN" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_TL" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_TI" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_UR" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_AM" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_SO" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_RU" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_ZH_HANS" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_ZH_HANT" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_ES" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_KO" \
-    "$REDCAP_API_TOKEN_SCAN_IRB_VI" \
-    "$REDCAP_API_TOKEN_SCAN_KIOSK";
+    "REDCAP_API_TOKEN_SFS_KIOSK" \
+    "REDCAP_API_TOKEN_SFS_SHELTERS" \
+    "REDCAP_API_TOKEN_SFS_SWAB_N_SEND" \
+    "REDCAP_API_TOKEN_SFS_SHELTERS" \
+    "REDCAP_API_TOKEN_SWAB_N_SEND_HEALTHCARE_WORKER" \
+    "REDCAP_API_TOKEN_SFS_ASYMPTOMATIC" \
+    "REDCAP_API_TOKEN_SFS_SWAB_N_SEND_HOME_FLU" \
+    "REDCAP_API_TOKEN_SWAB_N_SEND_ASYMPTOMATIC" \
+    "REDCAP_API_TOKEN_SCAN_EN" \
+    "REDCAP_API_TOKEN_SCAN_VI" \
+    "REDCAP_API_TOKEN_SCAN_ZH_HANS" \
+    "REDCAP_API_TOKEN_SCAN_ES" \
+    "REDCAP_API_TOKEN_SCAN_ZH_HANT" \
+    "REDCAP_API_TOKEN_SCAN_RU" \
+    "REDCAP_API_TOKEN_SCAN_SO" \
+    "REDCAP_API_TOKEN_SCAN_KO" \
+    "REDCAP_API_TOKEN_SCAN_AM" \
+    "REDCAP_API_TOKEN_SCAN_TI" \
+    "REDCAP_API_TOKEN_SCAN_TL" \
+    "REDCAP_API_TOKEN_SCAN_IRB_EN" \
+    "REDCAP_API_TOKEN_SCAN_IRB_TL" \
+    "REDCAP_API_TOKEN_SCAN_IRB_TI" \
+    "REDCAP_API_TOKEN_SCAN_IRB_UR" \
+    "REDCAP_API_TOKEN_SCAN_IRB_AM" \
+    "REDCAP_API_TOKEN_SCAN_IRB_SO" \
+    "REDCAP_API_TOKEN_SCAN_IRB_RU" \
+    "REDCAP_API_TOKEN_SCAN_IRB_ZH_HANS" \
+    "REDCAP_API_TOKEN_SCAN_IRB_ZH_HANT" \
+    "REDCAP_API_TOKEN_SCAN_IRB_ES" \
+    "REDCAP_API_TOKEN_SCAN_IRB_KO" \
+    "REDCAP_API_TOKEN_SCAN_IRB_VI" \
+    "REDCAP_API_TOKEN_SCAN_KIOSK";
 do
-    REDCAP_API_TOKEN="$token" ./dev/import-redcap-user \
-        --permissions <(REDCAP_API_TOKEN="$token" ./dev/export-redcap-user --net-id "$SRC_USER") \
+    if ! REDCAP_API_TOKEN="${!token}" ./dev/import-redcap-user \
+        --permissions <(REDCAP_API_TOKEN="${!token}" ./dev/export-redcap-user --net-id "$SRC_USER") \
         --net-id "$DST_USER"
+    then
+        echo "Failed to import user for token $token" >&2
+        echo >&2
+    fi
+
 done;
